[[redirects]]
from = "/"
to = "https://designsurvey.us/philly"
status = 301
force = true

[[redirects]]
from = "/about"
to = "https://designsurvey.us/philly/about"
status = 301
force = true

[[redirects]]
from = "/thanks"
to = "https://designsurvey.us/philly/thanks"
status = 301
force = true


[[redirects]]
from = "https://designsurvey.us/philly/wip-wip"
to = "https://designsurvey.us/philly"
status = 301
force = true